const basicDigitalData = {
  pageInstanceID: '755ebb86-60b5-451e-92d3-044157d29965',
  page: {
    pageInfo: {
      pageID: '1745',
      pageName: 'The Fruit Shoppe',
      destinationURL: 'https://fruitshoppe.firebaseapp.com/',
      referringURL: 'https://www.google.com/url?&q=The%20Fruit%20Shoppe',
      sysEnv: 'desktop',
      variant: '2',
      version: '1.14',
      breadcrumbs: ['home', 'Products'],
      author: 'D Falco',
      issueDate: '2020-06-23',
      effectiveDate: '2020-07-23',
      expiryDate: '2021-06-23',
      language: 'en-US',
      industryCodes: '7372',
      publisher: 'FullStory',
    },
    category: {
      primaryCategory: 'homepage',
    },
  },
  product: [{
    productInfo: {
      productID: '668ebb86-60b5-451e-92d3-044157d27823',
      productName: 'Cosmic Crisp Apple',
      description: 'A crisp and cosmic apple',
      productURL: 'https://fruitshoppe.firebaseapp.com/product/668ebb86-60b5-451e-92d3-044157d27823',
      productImage: 'https://fruitshoppe.firebaseapp.com/product/668ebb86-60b5-451e-92d3-044157d27823/image',
      productThumbnail: 'https://fruitshoppe.firebaseapp.com/product/668ebb86-60b5-451e-92d3-044157d27823/thumbnail',
      manufacturer: 'Washington State Apple Farm',
      sku: 'cca-1234',
      color: 'red and white',
      size: 'medium',
    },
    category: {
      primaryCategory: 'fruit',
    },
    linkedProduct: [],
  }],
  cart: {
    cartID: 'cart-1234',
    price: {
      basePrice: 15.55,
      voucherCode: '',
      voucherDiscount: 0,
      currency: 'USD',
      taxRate: 0.09,
      shipping: 5.0,
      shippingMethod: 'UPS-Ground',
      priceWithTax: 16.95,
      cartTotal: 21.95,
    },
    item: [{
      productInfo: {
        productID: '668ebb86-60b5-451e-92d3-044157d27823',
        productName: 'Cosmic Crisp Apple',
        description: 'A crisp and cosmic apple',
        productURL: 'https://fruitshoppe.firebaseapp.com/product/668ebb86-60b5-451e-92d3-044157d27823',
        productImage: 'https://fruitshoppe.firebaseapp.com/product/668ebb86-60b5-451e-92d3-044157d27823/image',
        productThumbnail: 'https://fruitshoppe.firebaseapp.com/product/668ebb86-60b5-451e-92d3-044157d27823/thumbnail',
        manufacturer: 'Washington State Apple Farm',
        sku: 'cca-1234',
        color: 'red and white',
        size: 'medium',
      },
      category: { primaryCategory: 'fruit' },
      price: {
        basePrice: 15.55,
        voucherCode: '',
        voucherDiscount: 0,
        currency: 'USD',
        taxRate: 0.09,
        shipping: 5.0,
        shippingMethod: 'UPS-Ground',
        priceWithTax: 16.95,
      },
      quantity: 1,
      linkedProduct: [],
      attributes: {},
    }],
    attributes: {},
  },
  transaction: {
    transactionID: 'tr-235098236',
    profile: {
      profileInfo: {
        profileID: 'pr-12333211',
        userName: 'JohnyAppleseed',
      },
      address: {
        line1: '123 Easy St.',
        line2: '',
        city: 'Athens',
        stateProvince: 'GA',
        postalCode: '30606',
        country: 'USA',
      },
      shippingAddress: {
        line1: '123 Easy St.',
        line2: '',
        city: 'Athens',
        stateProvince: 'GA',
        postalCode: '30606',
        country: 'USA',
      },
    },
    total: {
      basePrice: 15.55,
      voucherCode: '',
      voucherDiscount: 0,
      currency: 'USD',
      taxRate: 0.09,
      shipping: 5.0,
      shippingMethod: 'UPS-Ground',
      priceWithTax: 16.95,
      transactionTotal: 16.95,
    },
    attributes: {},
    item: [{
      productInfo: {
        productID: '668ebb86-60b5-451e-92d3-044157d27823',
        productName: 'Cosmic Crisp Apple',
        description: 'A crisp and cosmic apple',
        productURL: 'https://fruitshoppe.firebaseapp.com/product/668ebb86-60b5-451e-92d3-044157d27823',
        productImage: 'https://fruitshoppe.firebaseapp.com/product/668ebb86-60b5-451e-92d3-044157d27823/image',
        productThumbnail: 'https://fruitshoppe.firebaseapp.com/product/668ebb86-60b5-451e-92d3-044157d27823/thumbnail',
        manufacturer: 'Washington State Apple Farm',
        sku: 'cca-1234',
        color: 'red and white',
        size: 'medium',
      },
      category: { primaryCategory: 'fruit' },
      price: {
        basePrice: 15.55,
        voucherCode: '',
        voucherDiscount: 0,
        currency: 'USD',
        taxRate: 0.09,
        shipping: 5.0,
        shippingMethod: 'UPS-Ground',
        priceWithTax: 16.95,
      },
      quantity: 1,
      linkedProduct: [],
      attributes: {},
    }],
  },
  event: [{
    eventInfo: {
      eventName: 'Cart Item Added',
      eventAction: 'cart-item-added',
      eventPoints: 11,
      type: 'cart-modifier',
      timeStamp: new Date(),
      effect: 'cart has a new item',
    },
    category: {
      primaryCategory: 'cart',
      attributes: {},
    },
  }],
  component: [{
    componentInfo: {
      componentID: 'c-54123',
      componentName: 'Cosmic Crisp Promo Video',
      description: 'A video showing you just how cosmic and just how crisp is this apple.',
    },
    category: {
      primaryCategory: 'promo-video',
      componentType: 'video',
      attributes: {},
    },
  }],
  user: {
    segment: {},
    profile: [{
      profileInfo: {
        profileID: 'pr-12333211',
        userName: 'JohnyAppleseed',
      },
      address: {
        line1: '123 Easy St.',
        line2: '',
        city: 'Athens',
        stateProvince: 'GA',
        postalCode: '30606',
        country: 'USA',
      },
      social: {},
      attributes: {},
    }],
  },
  privacy: {
    accessCategories: [{
      categoryName: 'analytics',
      domains: ['fruitshoppe.firebaseapp.com'],
    }],
  }
};

export default basicDigitalData;
